---
ansible_connection: local

jenkins:
  JENKINS_NAMESPACE: "{{ ci_cd_namespace }}"


openshift_cluster_content:
- object: projectrequest
  content:
  - name: ci-cd
    template: "https://raw.githubusercontent.com/redhat-cop/cluster-lifecycle/v3.9.0/files/projectrequest/template.yml"
    action: create
    params: "{{ playbook_dir }}/params/projectrequests/ci-cd"
    tags:
    - projects
  - name: dev
    template: "https://raw.githubusercontent.com/redhat-cop/cluster-lifecycle/v3.9.0/files/projectrequest/template.yml"
    action: create
    params: "{{ playbook_dir }}/params/projectrequests/dev"
    tags:
    - projects
  - name: demo
    template: "https://raw.githubusercontent.com/redhat-cop/cluster-lifecycle/v3.9.0/files/projectrequest/template.yml"
    action: create
    params: "{{ playbook_dir }}/params/projectrequests/test"
    tags:
    - projects
- object: group-role-binding
  content:
  - name: "ci-cd-acl"
    namespace: "{{ ci_cd_namespace }}"
    template: "{{ playbook_dir }}/openshift-templates/rolebinding-group/template.yml"
    params: "{{ playbook_dir }}/params/rolebinding-group/all"
    tags:
    - rolebinding-group
  - name: "labs-dev-acl"
    namespace: "{{ dev_namespace }}"
    template: "{{ playbook_dir }}/openshift-templates/rolebinding-group/template.yml"
    params: "{{ playbook_dir }}/params/rolebinding-group/all"
    tags:
    - rolebinding-group
  - name: "labs-dev-acl"
    namespace: "{{ test_namespace }}"
    template: "{{ playbook_dir }}/openshift-templates/rolebinding-group/template.yml"
    params: "{{ playbook_dir }}/params/rolebinding-group/all"
    tags:
    - rolebinding-group
- object: jenkins-role-binding
  content:
  - name: "jenkins-{{ dev_namespace }}-role-binding"
    template: "{{ playbook_dir }}/openshift-templates/rolebinding-jenkins/rolebinding-template-jenkins.yml"
    params_from_vars: "{{ jenkins }}"
    namespace: "{{ dev_namespace }}"
    tags:
    - "{{ dev_namespace }}"
    - rolebinding-jenkins
    - "rolebinding-jenkins-{{ dev_namespace }}"
  - name: "jenkins-{{ test_namespace }}-role-binding"
    template: "{{ playbook_dir }}/openshift-templates/rolebinding-jenkins/rolebinding-template-jenkins.yml"
    params_from_vars: "{{ jenkins }}"
    namespace: "{{ test_namespace }}"
    tags:
    - "{{ test_namespace }}"
    - rolebinding-jenkins
    - "rolebinding-jenkins-{{ test_namespace }}"
